version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    depends_on:
      - db 

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: PHPizza
      # MYSQL_DATABASE: PHPizza
      # MYSQL_USER: Elijah
      # MYSQL_PASSWORD: PHPizza123!
    ports:
      - 3306:3306
    volumes:
      - ./db/db_data/data:/var/lib/mysql
      - ./db/db_init:/docker-entrypoint-initdb.d

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     PMA_HOST: db
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - db

# volumes:
#   db_data