<?php 
    /* Login form that validates the user's email and password 
    input and checks if the provided credentials match a user in 
    the database. If the user's input is valid the script sets a 
    session variable indicating that the user is logged in and 
    redirects the user to a homepage. If there are validation 
    errors or the email and password do not match a user in the 
    database we display an error message. */
    session_start();
    $email = "";
    $password = "";
    $errors = ['email'=>'', 'password'=>''];

    if(isset($_POST['submit'])){
        $errors = validateInputs($email, $password);
        if (!array_filter($errors)) {
            if (isValidUser($email, $password)) {
                $_SESSION["loggedin"] = true;
                $_SESSION["user"] = $email;
                header("Location: /PHPizza/index.php");
                exit;
            }
            else {
                $error = 'Invalid email or password.';
            } 
        }
        
    }


    /* This function takes two arguments, an email and a password,
    and return true if there is a user in the users table with 
    the same credentials */
    function isValidUser($email, $password) {
        include('../config/db_connect.php');
        $query = "SELECT * FROM users WHERE email = ? AND password = ?";
        $stmt = mysqli_prepare($connection, $query);
        mysqli_stmt_bind_param($stmt, "ss", $email, $password);
        mysqli_stmt_execute($stmt);
        $result = mysqli_stmt_get_result($stmt);
        $row_count = mysqli_num_rows($result);
        if (!$row_count) {
            return false;
        }
        return true;
    }

    
    /* Takes $email and $password by reference and validates them.
    The function returns an array of errors that might have been
    generated by the two validation functions used */
    function validateInputs(&$email, &$password) {
        $errors['email'] = emailValidation($email);
        $errors['password'] = passwordValidation($password);
        return $errors;
    }


    /* Validates and sets $email. If the email address is empty,
    or not valid the function returns an error message and sets
    the email address to an empty string, else set the $email to 
    the validated value */
    function emailValidation(&$email) {
        $error = '';
        if (empty($_POST['email'])) {
            $error = 'An email is required';
        } 
        else {
          $email = $_POST['email'];
          if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            $error = 'enter a valid email address';
            $email = '';
          }
        }
        return $error;
    }


    /* Validates and sets $password. If the password is empty or 
    the password does not meet our regex criteria, the function 
    returns an error message and sets the password variable to an 
    empty string. Our regular expression pattern verifies that the 
    password contains at least eight characters, at least one 
    uppercase letter, one lowercase letter, one number, and one 
    special character. If the password meets the criteria, the 
    function sets the password variable and returns an empty 
    string. */
    function passwordValidation(&$password) {
        $error = '';
        if (empty($_POST['password'])) {
            $error = 'A password is required';
        }
        else {
            $password = $_POST['password'];
            if (!preg_match('/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/', $password)) {
                $error = 'Password must contain minimum eight characters, at least one uppercase letter, one lowercase letter, one number, and one special character';
                $password = '';
            }
        }
        return $error;
    }
?>

<!DOCTYPE html>
<html>
    <?php include('../templates/header.php'); ?>
    <div class="row">
    <div class="col s12 m6 offset-m3">
        <div class="card">
        <div class="card-content">
            <span class="card-title center">Log in to PHPizza</span>
            <form method="post" action="login.php">
            <div class="input-field">
                <!-- <input id="email" type="email" name="email" required> -->
                <input type="text" name="email" value="<?php echo htmlspecialchars($email); ?>">
                <label for="email">Email</label>
                <div class="red-text"><?php echo htmlspecialchars($errors['email']);?></div>
            </div>
            <div class="input-field">


                <!-- <input id="password" type="password" name="password" required> -->
                <input type="password" name="password" value="<?php echo htmlspecialchars($password); ?>">
                <label for="password">Password</label>

                <div class="red-text"><?php echo htmlspecialchars($errors['password']);?></div>
            </div>
            <!-- <div class="center">
                <button type="submit" value="submit" class="btn orange waves-effect waves-light">Log in</button>
            </div> -->
            <div class="center">
                <input type="submit" value="submit" name="submit" class="btn brand z-depth-0">
            </div>
            </form>
            <div class="center">
            <a href="register.php">Don't have an account? Register now</a>
            </div>
        </div>
        </div>
    </div>
    </div>

    <?php if (isset($error)): ?>
    <div class="row">
        <div class="col s12 m6 offset-m3">
        <div class="card red lighten-4">
            <div class="card-content">
            <span class="card-title center"><?= $error ?></span>
            </div>
        </div>
        </div>
    </div>
    <?php endif; ?>

    <?php include('../templates/footer.php'); ?>
</html>